/**
 * SCS Status Page API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GetImpactType200Response } from '../model/models';
import { GetImpactTypes200Response } from '../model/models';
import { GetSeverities200Response } from '../model/models';
import { GetSeverity200Response } from '../model/models';
import { IdField } from '../model/models';
import { ImpactType } from '../model/models';
import { Severity } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ImpactServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a new impact type.
     * 
     * @param impactType Send an impact type.
     */
    createImpactType(impactType?: ImpactType, extraHttpRequestParams?: any): Observable<IdField>;

    /**
     * Create a new severity.
     * 
     * @param severity Send an impact type.
     */
    createSeverity(severity?: Severity, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete an impact type.
     * 
     * @param impactTypeId Impact type ID is required in path.
     */
    deleteImpactType(impactTypeId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete a specific severity.
     * 
     * @param severityName Severity name is required in path.
     */
    deleteSeverity(severityName: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get a specific impact type by id.
     * 
     * @param impactTypeId Impact type ID is required in path.
     */
    getImpactType(impactTypeId: string, extraHttpRequestParams?: any): Observable<GetImpactType200Response>;

    /**
     * Get a list of impact types.
     * 
     */
    getImpactTypes(extraHttpRequestParams?: any): Observable<GetImpactTypes200Response>;

    /**
     * Get the current list of severieties.
     * 
     */
    getSeverities(extraHttpRequestParams?: any): Observable<GetSeverities200Response>;

    /**
     * Get a specific severity by its name.
     * 
     * @param severityName Severity name is required in path.
     */
    getSeverity(severityName: string, extraHttpRequestParams?: any): Observable<GetSeverity200Response>;

    /**
     * Update a specific impact type.
     * 
     * @param impactTypeId Impact type ID is required in path.
     * @param impactType Send an impact type.
     */
    updateImpactType(impactTypeId: string, impactType?: ImpactType, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Update a specific severity.
     * 
     * @param severityName Severity name is required in path.
     * @param severity Send an impact type.
     */
    updateSeverity(severityName: string, severity?: Severity, extraHttpRequestParams?: any): Observable<{}>;

}
