// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Component defines model for Component.
type Component struct {
	// ActivelyAffectedBy A list of impacts for a component.
	// Impacts reference incidents.
	ActivelyAffectedBy *ImpactIncidentList `json:"activelyAffectedBy,omitempty"`

	// DisplayName Short and describing name.
	DisplayName *DisplayName `json:"displayName,omitempty"`

	// Labels Labels are free text key value pairs for components.
	Labels *Labels `json:"labels,omitempty"`
}

// ComponentResponseData defines model for ComponentResponseData.
type ComponentResponseData struct {
	// ActivelyAffectedBy A list of impacts for a component.
	// Impacts reference incidents.
	ActivelyAffectedBy *ImpactIncidentList `json:"activelyAffectedBy,omitempty"`

	// DisplayName Short and describing name.
	DisplayName *DisplayName `json:"displayName,omitempty"`

	// Id Identification for objects. UUID preferred.
	Id Id `json:"id"`

	// Labels Labels are free text key value pairs for components.
	Labels *Labels `json:"labels,omitempty"`
}

// Date Point in time. Nullable for open end timeframes.
type Date = time.Time

// Description A longer text with detailed information.
type Description = string

// DisplayName Short and describing name.
type DisplayName = string

// Generation Incremental as generation field for responses.
type Generation struct {
	// Generation Positive and incrementing number for ordering and identfication of e.g. sub resources.
	Generation Incremental `json:"generation"`
}

// Id Identification for objects. UUID preferred.
type Id = openapi_types.UUID

// IdField Id field for responses.
type IdField struct {
	// Id Identification for objects. UUID preferred.
	Id Id `json:"id"`
}

// Impact An impact connects a component and an incident with an impact type.
type Impact struct {
	// Reference Identification for objects. UUID preferred.
	Reference *Id `json:"reference,omitempty"`

	// Severity The severity of an impact affecting a component. Different impact types
	// might have different severities impacting different components.
	Severity *SeverityValue `json:"severity,omitempty"`

	// Type Identification for objects. UUID preferred.
	Type *Id `json:"type,omitempty"`
}

// ImpactComponentList A list of impacts for an incident.
// Impacts reference components.
type ImpactComponentList = []Impact

// ImpactIncidentList A list of impacts for a component.
// Impacts reference incidents.
type ImpactIncidentList = []Impact

// ImpactType defines model for ImpactType.
type ImpactType struct {
	// Description A longer text with detailed information.
	Description *Description `json:"description,omitempty"`

	// DisplayName Short and describing name.
	DisplayName *DisplayName `json:"displayName,omitempty"`
}

// ImpactTypeResponseData defines model for ImpactTypeResponseData.
type ImpactTypeResponseData struct {
	// Description A longer text with detailed information.
	Description *Description `json:"description,omitempty"`

	// DisplayName Short and describing name.
	DisplayName *DisplayName `json:"displayName,omitempty"`

	// Id Identification for objects. UUID preferred.
	Id Id `json:"id"`
}

// Incident defines model for Incident.
type Incident struct {
	// Affects A list of impacts for an incident.
	// Impacts reference components.
	Affects *ImpactComponentList `json:"affects,omitempty"`

	// BeganAt Point in time. Nullable for open end timeframes.
	BeganAt *Date `json:"beganAt"`

	// Description A longer text with detailed information.
	Description *Description `json:"description,omitempty"`

	// DisplayName Short and describing name.
	DisplayName *DisplayName `json:"displayName,omitempty"`

	// EndedAt Point in time. Nullable for open end timeframes.
	EndedAt *Date `json:"endedAt"`

	// Phase To reference a phase, its generation and order is needed.
	Phase *PhaseReference `json:"phase,omitempty"`

	// Updates List of Incrementals for referencing subresources.
	Updates *IncrementalList `json:"updates,omitempty"`
}

// IncidentResponseData defines model for IncidentResponseData.
type IncidentResponseData struct {
	// Affects A list of impacts for an incident.
	// Impacts reference components.
	Affects *ImpactComponentList `json:"affects,omitempty"`

	// BeganAt Point in time. Nullable for open end timeframes.
	BeganAt *Date `json:"beganAt"`

	// Description A longer text with detailed information.
	Description *Description `json:"description,omitempty"`

	// DisplayName Short and describing name.
	DisplayName *DisplayName `json:"displayName,omitempty"`

	// EndedAt Point in time. Nullable for open end timeframes.
	EndedAt *Date `json:"endedAt"`

	// Id Identification for objects. UUID preferred.
	Id Id `json:"id"`

	// Phase To reference a phase, its generation and order is needed.
	Phase *PhaseReference `json:"phase,omitempty"`

	// Updates List of Incrementals for referencing subresources.
	Updates *IncrementalList `json:"updates,omitempty"`
}

// IncidentUpdate An update is a sub resource to an incident.
// It's identified by the incident ID and its own order.
// Updates happen in a given order.
type IncidentUpdate struct {
	// CreatedAt Point in time. Nullable for open end timeframes.
	CreatedAt *Date `json:"createdAt"`

	// Description A longer text with detailed information.
	Description *Description `json:"description,omitempty"`

	// DisplayName Short and describing name.
	DisplayName *DisplayName `json:"displayName,omitempty"`
}

// IncidentUpdateResponseData defines model for IncidentUpdateResponseData.
type IncidentUpdateResponseData struct {
	// CreatedAt Point in time. Nullable for open end timeframes.
	CreatedAt *Date `json:"createdAt"`

	// Description A longer text with detailed information.
	Description *Description `json:"description,omitempty"`

	// DisplayName Short and describing name.
	DisplayName *DisplayName `json:"displayName,omitempty"`

	// Order Positive and incrementing number for ordering and identfication of e.g. sub resources.
	Order Incremental `json:"order"`
}

// Incremental Positive and incrementing number for ordering and identfication of e.g. sub resources.
type Incremental = int

// IncrementalList List of Incrementals for referencing subresources.
type IncrementalList = []Incremental

// Labels Labels are free text key value pairs for components.
type Labels map[string]string

// Order Incremental as order field for responses.
type Order struct {
	// Order Positive and incrementing number for ordering and identfication of e.g. sub resources.
	Order Incremental `json:"order"`
}

// Phase A single phase is just its name.
// It can be referenced by its generation and order.
// See: #/components/schemas/PhaseReference
type Phase = string

// PhaseList Phase resources are always handled as a list.
type PhaseList struct {
	Phases []Phase `json:"phases"`
}

// PhaseListResponseData defines model for PhaseListResponseData.
type PhaseListResponseData struct {
	// Generation Positive and incrementing number for ordering and identfication of e.g. sub resources.
	Generation Incremental `json:"generation"`
	Phases     []Phase     `json:"phases"`
}

// PhaseReference defines model for PhaseReference.
type PhaseReference struct {
	// Generation Positive and incrementing number for ordering and identfication of e.g. sub resources.
	Generation Incremental `json:"generation"`

	// Order Positive and incrementing number for ordering and identfication of e.g. sub resources.
	Order Incremental `json:"order"`
}

// Severity A severity has an identifying name and a numeric value.
type Severity struct {
	// DisplayName Short and describing name.
	DisplayName *DisplayName `json:"displayName,omitempty"`

	// Value The severity of an impact affecting a component. Different impact types
	// might have different severities impacting different components.
	Value *SeverityValue `json:"value,omitempty"`
}

// SeverityValue The severity of an impact affecting a component. Different impact types
// might have different severities impacting different components.
type SeverityValue = int

// ComponentAtQueryParameter Point in time. Nullable for open end timeframes.
type ComponentAtQueryParameter = Date

// ComponentIdPathParameter Identification for objects. UUID preferred.
type ComponentIdPathParameter = Id

// GenerationQueryParameter Positive and incrementing number for ordering and identfication of e.g. sub resources.
type GenerationQueryParameter = Incremental

// ImpactTypeIdPathParameter Identification for objects. UUID preferred.
type ImpactTypeIdPathParameter = Id

// IncidentIdPathParameter Identification for objects. UUID preferred.
type IncidentIdPathParameter = Id

// IncidentUpdateOrderPathParameter Positive and incrementing number for ordering and identfication of e.g. sub resources.
type IncidentUpdateOrderPathParameter = Incremental

// SeverityNamePathParameter Short and describing name.
type SeverityNamePathParameter = DisplayName

// ComponentListResponse defines model for ComponentListResponse.
type ComponentListResponse struct {
	Data []ComponentResponseData `json:"data"`
}

// ComponentResponse defines model for ComponentResponse.
type ComponentResponse struct {
	Data ComponentResponseData `json:"data"`
}

// GenerationResponse Incremental as generation field for responses.
type GenerationResponse = Generation

// IdResponse Id field for responses.
type IdResponse = IdField

// ImpactTypeListResponse defines model for ImpactTypeListResponse.
type ImpactTypeListResponse struct {
	Data []ImpactTypeResponseData `json:"data"`
}

// ImpactTypeResponse defines model for ImpactTypeResponse.
type ImpactTypeResponse struct {
	Data ImpactTypeResponseData `json:"data"`
}

// IncidentListResponse defines model for IncidentListResponse.
type IncidentListResponse struct {
	Data []IncidentResponseData `json:"data"`
}

// IncidentResponse defines model for IncidentResponse.
type IncidentResponse struct {
	Data IncidentResponseData `json:"data"`
}

// IncidentUpdateListResponse defines model for IncidentUpdateListResponse.
type IncidentUpdateListResponse struct {
	Data []IncidentUpdateResponseData `json:"data"`
}

// IncidentUpdateResponse defines model for IncidentUpdateResponse.
type IncidentUpdateResponse struct {
	Data IncidentUpdateResponseData `json:"data"`
}

// OrderResponse Incremental as order field for responses.
type OrderResponse = Order

// PhaseListResponse defines model for PhaseListResponse.
type PhaseListResponse struct {
	Data PhaseListResponseData `json:"data"`
}

// SeverityListResponse defines model for SeverityListResponse.
type SeverityListResponse struct {
	Data []Severity `json:"data"`
}

// SeverityResponse defines model for SeverityResponse.
type SeverityResponse struct {
	// Data A severity has an identifying name and a numeric value.
	Data Severity `json:"data"`
}

// ComponentRequest defines model for ComponentRequest.
type ComponentRequest = Component

// ImpactTypeRequest defines model for ImpactTypeRequest.
type ImpactTypeRequest = ImpactType

// IncidentRequest defines model for IncidentRequest.
type IncidentRequest = Incident

// IncidentUpdateRequest An update is a sub resource to an incident.
// It's identified by the incident ID and its own order.
// Updates happen in a given order.
type IncidentUpdateRequest = IncidentUpdate

// PhaseListRequest Phase resources are always handled as a list.
type PhaseListRequest = PhaseList

// SeverityRequest A severity has an identifying name and a numeric value.
type SeverityRequest = Severity

// GetComponentsParams defines parameters for GetComponents.
type GetComponentsParams struct {
	// At An optional at time stamp, used as reference time for the component.
	At *ComponentAtQueryParameter `form:"at,omitempty" json:"at,omitempty"`
}

// GetComponentParams defines parameters for GetComponent.
type GetComponentParams struct {
	// At An optional at time stamp, used as reference time for the component.
	At *ComponentAtQueryParameter `form:"at,omitempty" json:"at,omitempty"`
}

// GetIncidentsParams defines parameters for GetIncidents.
type GetIncidentsParams struct {
	// Start Start of time frame to query for (RFC3339).
	Start time.Time `form:"start" json:"start"`

	// End End of time frame to query for (RFC3339).
	End time.Time `form:"end" json:"end"`
}

// GetPhaseListParams defines parameters for GetPhaseList.
type GetPhaseListParams struct {
	// Generation Optional generation in query. E.g. ?generation=7
	Generation *GenerationQueryParameter `form:"generation,omitempty" json:"generation,omitempty"`
}

// CreateComponentJSONRequestBody defines body for CreateComponent for application/json ContentType.
type CreateComponentJSONRequestBody = Component

// UpdateComponentJSONRequestBody defines body for UpdateComponent for application/json ContentType.
type UpdateComponentJSONRequestBody = Component

// CreateImpactTypeJSONRequestBody defines body for CreateImpactType for application/json ContentType.
type CreateImpactTypeJSONRequestBody = ImpactType

// UpdateImpactTypeJSONRequestBody defines body for UpdateImpactType for application/json ContentType.
type UpdateImpactTypeJSONRequestBody = ImpactType

// CreateIncidentJSONRequestBody defines body for CreateIncident for application/json ContentType.
type CreateIncidentJSONRequestBody = Incident

// UpdateIncidentJSONRequestBody defines body for UpdateIncident for application/json ContentType.
type UpdateIncidentJSONRequestBody = Incident

// CreateIncidentUpdateJSONRequestBody defines body for CreateIncidentUpdate for application/json ContentType.
type CreateIncidentUpdateJSONRequestBody = IncidentUpdate

// UpdateIncidentUpdateJSONRequestBody defines body for UpdateIncidentUpdate for application/json ContentType.
type UpdateIncidentUpdateJSONRequestBody = IncidentUpdate

// CreatePhaseListJSONRequestBody defines body for CreatePhaseList for application/json ContentType.
type CreatePhaseListJSONRequestBody = PhaseList

// CreateSeverityJSONRequestBody defines body for CreateSeverity for application/json ContentType.
type CreateSeverityJSONRequestBody = Severity

// UpdateSeverityJSONRequestBody defines body for UpdateSeverity for application/json ContentType.
type UpdateSeverityJSONRequestBody = Severity

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get a list of components.
	// (GET /components)
	GetComponents(ctx echo.Context, params GetComponentsParams) error
	// Create a new component.
	// (POST /components)
	CreateComponent(ctx echo.Context) error
	// Delete a component.
	// (DELETE /components/{componentId})
	DeleteComponent(ctx echo.Context, componentId ComponentIdPathParameter) error
	// Get a specific component by id.
	// (GET /components/{componentId})
	GetComponent(ctx echo.Context, componentId ComponentIdPathParameter, params GetComponentParams) error
	// Update a component.
	// (PATCH /components/{componentId})
	UpdateComponent(ctx echo.Context, componentId ComponentIdPathParameter) error
	// Get a list of impact types.
	// (GET /impacttypes)
	GetImpactTypes(ctx echo.Context) error
	// Create a new impact type.
	// (POST /impacttypes)
	CreateImpactType(ctx echo.Context) error
	// Delete an impact type.
	// (DELETE /impacttypes/{impactTypeId})
	DeleteImpactType(ctx echo.Context, impactTypeId ImpactTypeIdPathParameter) error
	// Get a specific impact type by id.
	// (GET /impacttypes/{impactTypeId})
	GetImpactType(ctx echo.Context, impactTypeId ImpactTypeIdPathParameter) error
	// Update a specific impact type.
	// (PATCH /impacttypes/{impactTypeId})
	UpdateImpactType(ctx echo.Context, impactTypeId ImpactTypeIdPathParameter) error
	// Get a list of incidents between two points in time.
	// (GET /incidents)
	GetIncidents(ctx echo.Context, params GetIncidentsParams) error
	// Create a new incident.
	// (POST /incidents)
	CreateIncident(ctx echo.Context) error
	// Delete an incident.
	// (DELETE /incidents/{incidentId})
	DeleteIncident(ctx echo.Context, incidentId IncidentIdPathParameter) error
	// Get a specific incident by id.
	// (GET /incidents/{incidentId})
	GetIncident(ctx echo.Context, incidentId IncidentIdPathParameter) error
	// Update an incident.
	// (PATCH /incidents/{incidentId})
	UpdateIncident(ctx echo.Context, incidentId IncidentIdPathParameter) error
	// Get a list of updates from a specific incident.
	// (GET /incidents/{incidentId}/updates)
	GetIncidentUpdates(ctx echo.Context, incidentId IncidentIdPathParameter) error
	// Create a new update to a specific incident.
	// (POST /incidents/{incidentId}/updates)
	CreateIncidentUpdate(ctx echo.Context, incidentId IncidentIdPathParameter) error
	// Delete a specific update from a specific incident
	// (DELETE /incidents/{incidentId}/updates/{updateOrder})
	DeleteIncidentUpdate(ctx echo.Context, incidentId IncidentIdPathParameter, updateOrder IncidentUpdateOrderPathParameter) error
	// Get a specific update from a specific incident.
	// (GET /incidents/{incidentId}/updates/{updateOrder})
	GetIncidentUpdate(ctx echo.Context, incidentId IncidentIdPathParameter, updateOrder IncidentUpdateOrderPathParameter) error
	// Update a specific update from a specific incident.
	// (PATCH /incidents/{incidentId}/updates/{updateOrder})
	UpdateIncidentUpdate(ctx echo.Context, incidentId IncidentIdPathParameter, updateOrder IncidentUpdateOrderPathParameter) error
	// Get the current generation list of phases.
	// (GET /phases)
	GetPhaseList(ctx echo.Context, params GetPhaseListParams) error
	// Create a new generation of the phase list.
	// (POST /phases)
	CreatePhaseList(ctx echo.Context) error
	// Get the current list of severieties.
	// (GET /severities)
	GetSeverities(ctx echo.Context) error
	// Create a new severity.
	// (POST /severities)
	CreateSeverity(ctx echo.Context) error
	// Delete a specific severity.
	// (DELETE /severities/{severityName})
	DeleteSeverity(ctx echo.Context, severityName SeverityNamePathParameter) error
	// Get a specific severity by its name.
	// (GET /severities/{severityName})
	GetSeverity(ctx echo.Context, severityName SeverityNamePathParameter) error
	// Update a specific severity.
	// (PATCH /severities/{severityName})
	UpdateSeverity(ctx echo.Context, severityName SeverityNamePathParameter) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetComponents converts echo context to params.
func (w *ServerInterfaceWrapper) GetComponents(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetComponentsParams
	// ------------- Optional query parameter "at" -------------

	err = runtime.BindQueryParameter("form", true, false, "at", ctx.QueryParams(), &params.At)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter at: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetComponents(ctx, params)
	return err
}

// CreateComponent converts echo context to params.
func (w *ServerInterfaceWrapper) CreateComponent(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateComponent(ctx)
	return err
}

// DeleteComponent converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteComponent(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "componentId" -------------
	var componentId ComponentIdPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "componentId", ctx.Param("componentId"), &componentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter componentId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteComponent(ctx, componentId)
	return err
}

// GetComponent converts echo context to params.
func (w *ServerInterfaceWrapper) GetComponent(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "componentId" -------------
	var componentId ComponentIdPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "componentId", ctx.Param("componentId"), &componentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter componentId: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetComponentParams
	// ------------- Optional query parameter "at" -------------

	err = runtime.BindQueryParameter("form", true, false, "at", ctx.QueryParams(), &params.At)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter at: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetComponent(ctx, componentId, params)
	return err
}

// UpdateComponent converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateComponent(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "componentId" -------------
	var componentId ComponentIdPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "componentId", ctx.Param("componentId"), &componentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter componentId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateComponent(ctx, componentId)
	return err
}

// GetImpactTypes converts echo context to params.
func (w *ServerInterfaceWrapper) GetImpactTypes(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetImpactTypes(ctx)
	return err
}

// CreateImpactType converts echo context to params.
func (w *ServerInterfaceWrapper) CreateImpactType(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateImpactType(ctx)
	return err
}

// DeleteImpactType converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteImpactType(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "impactTypeId" -------------
	var impactTypeId ImpactTypeIdPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "impactTypeId", ctx.Param("impactTypeId"), &impactTypeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter impactTypeId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteImpactType(ctx, impactTypeId)
	return err
}

// GetImpactType converts echo context to params.
func (w *ServerInterfaceWrapper) GetImpactType(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "impactTypeId" -------------
	var impactTypeId ImpactTypeIdPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "impactTypeId", ctx.Param("impactTypeId"), &impactTypeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter impactTypeId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetImpactType(ctx, impactTypeId)
	return err
}

// UpdateImpactType converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateImpactType(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "impactTypeId" -------------
	var impactTypeId ImpactTypeIdPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "impactTypeId", ctx.Param("impactTypeId"), &impactTypeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter impactTypeId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateImpactType(ctx, impactTypeId)
	return err
}

// GetIncidents converts echo context to params.
func (w *ServerInterfaceWrapper) GetIncidents(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetIncidentsParams
	// ------------- Required query parameter "start" -------------

	err = runtime.BindQueryParameter("form", true, true, "start", ctx.QueryParams(), &params.Start)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter start: %s", err))
	}

	// ------------- Required query parameter "end" -------------

	err = runtime.BindQueryParameter("form", true, true, "end", ctx.QueryParams(), &params.End)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter end: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetIncidents(ctx, params)
	return err
}

// CreateIncident converts echo context to params.
func (w *ServerInterfaceWrapper) CreateIncident(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateIncident(ctx)
	return err
}

// DeleteIncident converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteIncident(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "incidentId" -------------
	var incidentId IncidentIdPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "incidentId", ctx.Param("incidentId"), &incidentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter incidentId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteIncident(ctx, incidentId)
	return err
}

// GetIncident converts echo context to params.
func (w *ServerInterfaceWrapper) GetIncident(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "incidentId" -------------
	var incidentId IncidentIdPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "incidentId", ctx.Param("incidentId"), &incidentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter incidentId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetIncident(ctx, incidentId)
	return err
}

// UpdateIncident converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateIncident(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "incidentId" -------------
	var incidentId IncidentIdPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "incidentId", ctx.Param("incidentId"), &incidentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter incidentId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateIncident(ctx, incidentId)
	return err
}

// GetIncidentUpdates converts echo context to params.
func (w *ServerInterfaceWrapper) GetIncidentUpdates(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "incidentId" -------------
	var incidentId IncidentIdPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "incidentId", ctx.Param("incidentId"), &incidentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter incidentId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetIncidentUpdates(ctx, incidentId)
	return err
}

// CreateIncidentUpdate converts echo context to params.
func (w *ServerInterfaceWrapper) CreateIncidentUpdate(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "incidentId" -------------
	var incidentId IncidentIdPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "incidentId", ctx.Param("incidentId"), &incidentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter incidentId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateIncidentUpdate(ctx, incidentId)
	return err
}

// DeleteIncidentUpdate converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteIncidentUpdate(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "incidentId" -------------
	var incidentId IncidentIdPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "incidentId", ctx.Param("incidentId"), &incidentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter incidentId: %s", err))
	}

	// ------------- Path parameter "updateOrder" -------------
	var updateOrder IncidentUpdateOrderPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "updateOrder", ctx.Param("updateOrder"), &updateOrder, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter updateOrder: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteIncidentUpdate(ctx, incidentId, updateOrder)
	return err
}

// GetIncidentUpdate converts echo context to params.
func (w *ServerInterfaceWrapper) GetIncidentUpdate(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "incidentId" -------------
	var incidentId IncidentIdPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "incidentId", ctx.Param("incidentId"), &incidentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter incidentId: %s", err))
	}

	// ------------- Path parameter "updateOrder" -------------
	var updateOrder IncidentUpdateOrderPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "updateOrder", ctx.Param("updateOrder"), &updateOrder, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter updateOrder: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetIncidentUpdate(ctx, incidentId, updateOrder)
	return err
}

// UpdateIncidentUpdate converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateIncidentUpdate(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "incidentId" -------------
	var incidentId IncidentIdPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "incidentId", ctx.Param("incidentId"), &incidentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter incidentId: %s", err))
	}

	// ------------- Path parameter "updateOrder" -------------
	var updateOrder IncidentUpdateOrderPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "updateOrder", ctx.Param("updateOrder"), &updateOrder, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter updateOrder: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateIncidentUpdate(ctx, incidentId, updateOrder)
	return err
}

// GetPhaseList converts echo context to params.
func (w *ServerInterfaceWrapper) GetPhaseList(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPhaseListParams
	// ------------- Optional query parameter "generation" -------------

	err = runtime.BindQueryParameter("form", true, false, "generation", ctx.QueryParams(), &params.Generation)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter generation: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPhaseList(ctx, params)
	return err
}

// CreatePhaseList converts echo context to params.
func (w *ServerInterfaceWrapper) CreatePhaseList(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreatePhaseList(ctx)
	return err
}

// GetSeverities converts echo context to params.
func (w *ServerInterfaceWrapper) GetSeverities(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSeverities(ctx)
	return err
}

// CreateSeverity converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSeverity(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateSeverity(ctx)
	return err
}

// DeleteSeverity converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteSeverity(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "severityName" -------------
	var severityName SeverityNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "severityName", ctx.Param("severityName"), &severityName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter severityName: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteSeverity(ctx, severityName)
	return err
}

// GetSeverity converts echo context to params.
func (w *ServerInterfaceWrapper) GetSeverity(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "severityName" -------------
	var severityName SeverityNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "severityName", ctx.Param("severityName"), &severityName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter severityName: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSeverity(ctx, severityName)
	return err
}

// UpdateSeverity converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateSeverity(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "severityName" -------------
	var severityName SeverityNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "severityName", ctx.Param("severityName"), &severityName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter severityName: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateSeverity(ctx, severityName)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/components", wrapper.GetComponents)
	router.POST(baseURL+"/components", wrapper.CreateComponent)
	router.DELETE(baseURL+"/components/:componentId", wrapper.DeleteComponent)
	router.GET(baseURL+"/components/:componentId", wrapper.GetComponent)
	router.PATCH(baseURL+"/components/:componentId", wrapper.UpdateComponent)
	router.GET(baseURL+"/impacttypes", wrapper.GetImpactTypes)
	router.POST(baseURL+"/impacttypes", wrapper.CreateImpactType)
	router.DELETE(baseURL+"/impacttypes/:impactTypeId", wrapper.DeleteImpactType)
	router.GET(baseURL+"/impacttypes/:impactTypeId", wrapper.GetImpactType)
	router.PATCH(baseURL+"/impacttypes/:impactTypeId", wrapper.UpdateImpactType)
	router.GET(baseURL+"/incidents", wrapper.GetIncidents)
	router.POST(baseURL+"/incidents", wrapper.CreateIncident)
	router.DELETE(baseURL+"/incidents/:incidentId", wrapper.DeleteIncident)
	router.GET(baseURL+"/incidents/:incidentId", wrapper.GetIncident)
	router.PATCH(baseURL+"/incidents/:incidentId", wrapper.UpdateIncident)
	router.GET(baseURL+"/incidents/:incidentId/updates", wrapper.GetIncidentUpdates)
	router.POST(baseURL+"/incidents/:incidentId/updates", wrapper.CreateIncidentUpdate)
	router.DELETE(baseURL+"/incidents/:incidentId/updates/:updateOrder", wrapper.DeleteIncidentUpdate)
	router.GET(baseURL+"/incidents/:incidentId/updates/:updateOrder", wrapper.GetIncidentUpdate)
	router.PATCH(baseURL+"/incidents/:incidentId/updates/:updateOrder", wrapper.UpdateIncidentUpdate)
	router.GET(baseURL+"/phases", wrapper.GetPhaseList)
	router.POST(baseURL+"/phases", wrapper.CreatePhaseList)
	router.GET(baseURL+"/severities", wrapper.GetSeverities)
	router.POST(baseURL+"/severities", wrapper.CreateSeverity)
	router.DELETE(baseURL+"/severities/:severityName", wrapper.DeleteSeverity)
	router.GET(baseURL+"/severities/:severityName", wrapper.GetSeverity)
	router.PATCH(baseURL+"/severities/:severityName", wrapper.UpdateSeverity)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9QcbW/buPmvENyA3QGq7aQHbDMwDLnk7magaLOmvQ+79gMtPbbZSpSOpJIzAv/3gaQk",
	"Uq+mHDnpAf3QSBT5vL/TjzhMkyxlwKTAy0ecEU4SkMD1X9fluyv53xz4/rZ8q15GIEJOM0lThpf4iqFU",
	"/5/EiEgkaQJISJJkAcoFRIgIxGEDHFgI5u0m5UjuAFUAzHCAqdrrd3UWDjAjCeAlJhIHWIQ7SIg6968c",
	"NniJ/zK3kM/NWzG/IRLw4RBYyFfRLZG7AcCrlWh1g6iC8veccogQZSgjcldBpf6wQIX2ABzg8iO8lDwH",
	"X2hXkYb1F2DAiQLnGJHflRTeVp8oMDW9Zuin2XaG/m1f/evvPQS1S7wJu2IhhwSYJLGGeZVkJJQf9hkc",
	"JbBZiuQ+g3Ekps4ZT6XxioU08hGHcuFIUKvtpwL0YxYRCe94BNwX4lx/glL1DfqOspJh349AJLfHno5J",
	"Q1bu4B44lfu3JIEjuJRLkQJnBNjCOeJkuG+oyGJi9jgowNU2IOSPaUShbg/fmzfqWZgyCUz/l2RZTEOt",
	"WPMvQiH06Hl0tbE5uEkUFiHi2smaAk4Ni925HxiGqNVqA08hhZNDU+w7CEuxpgaIUaBzgWN29wGqUEsN",
	"2+2OCHhDxeRUqjYekB8GDyimQqJ0gzK1XmiYSpWbGqRyX38h0honspSJhrYZipk3o+DLeJoBl4X2RkTq",
	"p1RCIrw1sjz4Rn19CLACVgUlnJM9Lq2EMTa/mSM+V4vS9RcIO3lyhQrjgjjInDOBSMUcC41mUAuSCUhw",
	"AuZTYlo3ZTb+OQnDIVzs1r6g2djIWJNocphW0c8U4sgTIIZWNw2D/xLq4Lqb59YHx0qIlu97FpXow35C",
	"bPs96ouwu/Lmz87s4mTRiCqeh8+daE/L5f5Y5SUZXUZLL8XuIkoSnSHcs/K+ixJnkQA3MNQJ1+SexqRx",
	"vnDpvLEZpj4L6VvnTR9x6IBXS10t6H0JlbOB8XMoWJEZ01a0/yycdZKACXGr4XQo0/t6ztCGl4SS3kO8",
	"v9psIJQQ/bj3c/uuH1YkjJwywZiKQoBjsob4qHy8MasOhxZ1OnKBm4IJJI7fbfDyN8/QM/AuR3zugEJX",
	"WVu1m9uUMoko09XdGXqbxzFZx6bOm2bAkEr61LsNJ4liXYA3KU+IxEslDvBKvcMBZsWHZfGmOF5ITtlW",
	"H+8e26pDozhlW+BIwh8SPVC5QxFIQmNdQzIH6uC+a+M6Zxs56y7lEhEWIfN8TdlWl6k6t3ISj66CXVkf",
	"Q0S4tdyN4o4mWJUIq93rcrytbT2mEOcqoLNLF4tXUQfcSgvoprAPhq/6AzFDHz+ublCmK/wcohpv85xG",
	"XSQqhbHjHD9C0MizpuriTaNufLWqd7Y1irg8TBlTuLrpqxYH16VreWvG8k24qz6ID/hBVdv0tbW/kjgH",
	"61y8KNRDj1oFplPXaima0Bxzg9xPbFW8sc0fp7zxieFgTP7ZdpklpDUj7QuoU4foAtSmIqfAyYFE71i8",
	"b5ixBtwfCh41XGvdwg26GGfpE5xTvwy0st7JvY1bcO7UzbIE3Hbp2pV7MqUuzIcAr2FL2JX06ykGL8CU",
	"AAOLIPIHUUe5XtH2+8oGHYKi6SNGuJOi1OxnWruS6umFqOoTDMFQlO27zHzRPaM6wMzXyvGkOQ8BybRp",
	"0uTfBKKFM4QIrfe6j02dzqHyC1QKlD6UedUnZs4WaEcyFQ1Rhgja0nuwK1qeIuRA5BgBeBHD4cqARgUf",
	"Z8FpwlAktMG4Hk0PNFVo1BHJCqpyBcPGcqWO9/JkDdyEPgoW9UwvUudVkVG6QTDbzmpiVDiRhDKa5Ale",
	"LiqgKJOw1Wjhpoa1IHtTuDFnoSjCJKPPCiCRr+2p3o7LjRWPe683VSpDooiaqYTbmuy24r0GJnoDRDig",
	"DQcw4fpX2KN7Fb6gjFBuMHO7IR2MNCJxLMY2PXGvqDItNzw1su5XgdvSPDejE0HZNoaiSEEF+pILqe2H",
	"zi+UxUEhYWgNNjrRZkctcdIHJYmlLbkDWCIP+6+lssUr209sK4cGshIwzUESP5C9smwsis2sDylqLU3q",
	"msajd63EUOxYoaTYtJfkrdKSt8Fx+0eBdwu2F5D3buQ/pclz4fzcVLUPqRPUFqWwoFd2lPwxgMhkcS08",
	"7pxspCXG5fTGjphKp/GR+zJTNumSMqLAaWg0vS0ip0dLesORadJhAMdfy/0a9NyBRTXdOPmeiUe1U3By",
	"C3RDN5r8stbK+sQSut1JtCP3gKJqiS1uFavVdvZ1M3tKyB/GoVwsFsPuRaFK2SbVxpnKWL28u75Dd5LI",
	"XKBbsgV0dbvCAb4HLgyqF7OL2aUiSZoBIxnFS/x6tphdKqYRudP8mtcnCLegjYbiqJasVYSX+Bew4bfQ",
	"H9sxwx4FsEvm/WOISthrMwOXi0WfAFTr5t2DBbqSmCcJ4XsDcU9LPsCSbBXcdgYQf1bBdyo6ML/WIZwt",
	"qLlTRft+UJ3Bo3lr6ujQQvriONJOJ7uOqYGwGBCpDWN24XkIXIbPH505yINRlRhMhF2nw41+7tLhRBlo",
	"TvB1iMAPHdW7PAxBiE0ez9DbFF0XJe86JQyM9fmEPm4fFfMJMQxeTkMGtUNkENINDZ2CmApKogEdITLc",
	"telmIvWzCcf0+naqhBlEfSRM6Zmx/9pZDFlWWz8R+BRm90yWDNnD+kiGxcA8P2oOnYrPCfxpjz6e0SA2",
	"KrktRBt8mj+6U8seFrFGinFS3z+DfQabyI5SIvAQ0PPiOErW/Sybg3TbtrnSPmTYzoj/GVTnybati3j9",
	"ulMW2QctXLWoRb8GoJJwbaDMDRO1EsnUXJDQif9373++fv369T+/77tsItQOgyPkEWxIHku8xJeLy8tX",
	"i4tXi4sPF4ul/jdbXCz+19fZbKTZyq/Xwf9JJWFPAB5Y5A/6D08B/TTl65poG3QzJd/RGuQDAEPyIUVZ",
	"StWjstPsSlZZBD7qgMqFp+hQY9L9nM6nGhbrxLGmP/NHewnFx+9YCoy0SD03ac7jc4YJEBy1GOdEb4TE",
	"ezqbsoPQ9jQ1wR70NedBfHIdeaqXYacrx9zpdx2Tn6Jp842IUcec6JD5LPBEG54mXXL2JNNZdFe+CTGr",
	"3/U5ySDXJzAHbHLRJ5TpCIoel8X5o3PzboT5npoLgfenvRcUz1GQqQhdUL9Pok91E38OMo62FH5u5whN",
	"n+aHvlnKnsnUTJc9ncYWZWpsk61P7m2zaixjei+rnyav7VHztqjqHwnIuW5/OB2r5l1GSw4zBnPMkbk0",
	"GC0OrZucJzmdjptvA57HwV0liTuoTbW30VeiYLtJQ+JwZ1edwsTOafphPtbH08HMco+uI1bNyBM42Lz3",
	"Op0q15hWNgp7CyCWQ/NH9xq7RxDgoD9Oiftv5J/VeQ/SIjgmnWdGc4Sc+7nVqkVcDGpUs+Ijq4dnQ/+b",
	"UZi27xvWGj0Uze97SoDpPXCgW4au4zSP0J0k4VeU5euYhqgogCHzudo95zFe4p2UmVjO50L3wl+RjM6+",
	"/kPMRChmYZokOTP3dVrjWGlIYhTBPcRplpjufXvj5Xweq4W7VMjl68ViYSZEDFrNLf+jZ2iErQVY91YU",
	"+bJiJqb3SzPIPGv+kMrAJ/X2dvMXbobOsrc1W7+Fgg+fD/8PAAD//wLQHhBfSAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
