/**
 * SCS Status Page API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Impact } from './impact';


export interface Component { 
    /**
     * Short and describing name.
     */
    displayName?: string;
    /**
     * Labels are free text key value pairs for components.
     */
    labels?: { [key: string]: string; };
    /**
     * A list of impacts for a component. Impacts reference incidents. 
     */
    readonly activelyAffectedBy?: Array<Impact>;
}

