/**
 * SCS Status Page API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Incremental as generation field for responses.
 */
export interface Generation { 
    /**
     * Positive and incrementing number for ordering and identfication of e.g. sub resources. 
     */
    generation: number;
}

