/**
 * SCS Status Page API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An impact connects a component and an incident with an impact type.
 */
export interface Impact { 
    /**
     * Identification for objects. UUID preferred.
     */
    type?: string;
    /**
     * Identification for objects. UUID preferred.
     */
    reference?: string;
    /**
     * The severity of an impact affecting a component. Different impact types might have different severities impacting different components. 
     */
    severity?: number;
}

