/**
 * SCS Status Page API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ImpactTypeResponseData { 
    /**
     * Identification for objects. UUID preferred.
     */
    id: string;
    /**
     * Short and describing name.
     */
    displayName?: string;
    /**
     * A longer text with detailed information.
     */
    description?: string;
}

