/**
 * SCS Status Page API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IncidentUpdateResponseData { 
    /**
     * Positive and incrementing number for ordering and identfication of e.g. sub resources. 
     */
    order: number;
    /**
     * Short and describing name.
     */
    displayName?: string;
    /**
     * A longer text with detailed information.
     */
    description?: string;
    /**
     * Point in time. Nullable for open end timeframes.
     */
    createdAt?: string | null;
}

