/**
 * SCS Status Page API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Impact } from './impact';
import { PhaseReference } from './phaseReference';


export interface Incident { 
    /**
     * Short and describing name.
     */
    displayName?: string;
    /**
     * A longer text with detailed information.
     */
    description?: string;
    /**
     * List of Incrementals for referencing subresources.
     */
    readonly updates?: Array<number>;
    /**
     * A list of impacts for an incident. Impacts reference components. 
     */
    affects?: Array<Impact>;
    /**
     * Point in time. Nullable for open end timeframes.
     */
    beganAt?: string | null;
    /**
     * Point in time. Nullable for open end timeframes.
     */
    endedAt?: string | null;
    phase?: PhaseReference;
}

