/**
 * SCS Status Page API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A severity has an identifying name and a numeric value.
 */
export interface Severity { 
    /**
     * Short and describing name.
     */
    displayName?: string;
    /**
     * The severity of an impact affecting a component. Different impact types might have different severities impacting different components. 
     */
    value?: number;
}

